export default {
    "Nagasaki": ["Chimera", "Carbon RS", "BF400", "Dinghy", "Blazer", "Blazer Lifeguard", "Hot Rod Blazer", "Blazer Aqua", "Shotaro", "Street Blazer", "Havok", "Ultralight"],
    "Albany": ["Hermes", "Roosevelt", "Alpha", "Washington", "Cavalcade", "Lurcher", "Buccaneer", "Emperor", "Manana", "Primo", "Virgo", "Fränken Stange", "Primo Custom", "Buccaneer Custom", "Roosevelt Valor"],
    "Dundreary": ["Virgo Classic", "Landstalker", "Regina", "Stretch", "Virgo Classic Custom"],
    "Vapid": ["Hotknife", "Dominator", "Trophy Truck", "Speedo Custom", "Chino", "Future Shock Slamvan", "Apocalypse Imperator", "Hustler", "Contender", "Clown Van", "Slamvan", "Sadler", "Lost Slamvan", "Sandking SWB", "Bobcat XL", "Slamvan Custom", "Caracara", "FMJ", "Future Shock Imperator", "Nightmare Slamvan", "Peyote", "Retinue", "GB200", "Benson", "Bullet", "Minivan", "Radius", "Sandking XL", "Speedo", "Stanier", "Liberator", "Minivan Custom", "Desert Raid", "Pisswasser Dominator", "Guardian", "Chino Custom", "Blade", "Nightmare Dominator", "Apocalypse Slamvan", "Apocalypse Dominator", "Future Shock Dominator", "Clique", "Nightmare Imperator", "Riata", "Flash GT", "Ellie", "Dominator GTX"],
    "Brute": ["Tipper", "Boxville", "Pony", "Stockade", "Camper"],
    "Pegassi": ["Faggio", "Speeder", "Reaper", "Tempesta", "Vacca", "Infernus", "FCR 1000", "Oppressor", "Tezeract", "Torero", "Osiris", "Esskey", "Oppressor Mk II", "Monroe", "Bati 801", "Bati 801RR", "Ruffian", "FCR 1000 Custom", "Faggio Mod", "Faggio Sport", "Vortex", "Infernus Classic", "Zentorno", "Toros"],
    "Bravado": ["Youga", "Sprunk Buffalo", "Redwood Gauntlet", "Banshee 900R", "Buffalo S", "Future Shock Sasquatch", "Youga Classic", "Verlierer", "Rumpo", "Rumpo Custom", "Paradise", "Apocalypse Sasquatch", "Bison", "Duneloader", "Banshee", "Buffalo", "Gresley", "Gauntlet", "Rat-Truck", "Half-track", "Nightmare Sasquatch"],
    "Benefactor": ["Glendale", "Surano", "Apocalypse Bruiser", "Dubsta", "XLS", "Serrano", "Schafter LWB", "Streiter", "Schafter LWB (Armored)", "Feltzer", "Schafter", "Schwartzer", "Stirling GT", "Turreted Limo", "Schafter V12", "Schafter V12 (Armored)", "XLS (Armored)", "Panto", "Dubsta 6x6", "Terrorbyte", "Future Shock Bruiser", "Nightmare Bruiser", "Schlagen GT"],
    "Canis": ["Kalahari", "Crusader", "Mesa", "Seminole", "Bodhi", "Freecrawler", "Kamacho"],
    "Invetero": ["Coquette", "Coquette BlackFin", "Coquette Classic"],
    "Gallivanter": ["Baller", "Baller LE (Armored)", "Baller LE LWB", "Baller LE LWB (Armored)", "Baller LE"],
    "Ocelot": ["Ardent", "Lynx", "Swinger", "Pariah", "Stromberg", "XA-21", "F620", "Jackal", "Penetrator"],
    "Buckingham": ["Miljet", "Luxor", "SuperVolito", "Swift Deluxe", "Vestra", "Shamal", "Luxor Deluxe", "Swift", "SuperVolito Carbon", "Nimbus", "Volatus", "Alpha-Z1", "Pyro", "Howard NX-25"],
    "JoBuilt": ["Phantom Custom", "Hauler Custom", "Hauler", "Rubble", "Phantom", "Phantom Wedge"],
    "Unknown": ["Freight Train", "Festival Bus", "Police Maverick", "Cargo Plane", "Trailer", "Dock Handler", "Volatol", "Cruiser", "Police Transporter", "Lifeguard", "Utility Truck", "Boat Trailer", "Space Docker", "Barracks", "Armored Boxville", "Park Ranger", "Frogger", "Buzzard", "Submersible", "Rhino Tank", "Buzzard Attack Chopper", "Annihilator", "Duster", "P-45 Nokota", "Skylift", "Jet", "Velum 5-Seater", "FIB", "Whippet Race Bike", "BMX", "Caddy", "Ambulance", "Akula", "Airport Bus", "Cargobob", "Mobile Operations Center", "Valkyrie MOD.0", "Airtug", "V-65 Molotok", "Tractor", "B-11 Strikeforce", "Lawn Mower", "Police Cruiser", "Trashmaster", "Sheriff SUV", "Fire Truck", "Tourbus", "Taco Van", "Titan", "Bus", "Army Trailer", "Dashound", "Boxville", "Atomic Blimp", "Cable Car", "Docktug", "Prison Bus", "Unmarked Cruiser", "Police Rancher", "Police Roadcruiser", "Rat-Loader", "Rental Shuttle Bus", "Police Riot", "Ripley", "Scrap Truck", "Sheriff Cruiser", "Taxi", "Baletrailer", "Tipper", "Towtruck", "Scorcher", "Endurex Race Bike", "Tri-Cycles Race Bike", "Fixter", "Police Bike", "Maverick", "Cuban 800", "Mallard", "Mammatus", "P-996 LAZER", "Police Predator", "Velum", "Ramp Buggy", "Kraken", "Xero Blimp", "Tug", "Savage", "Valkyrie", "Blimp", "RC Bandito", "TM-02 Khanjali", "Barrage", "Chernobog", "RCV", "Sea Sparrow", "Vigilante", "RM-10 Bombushka", "FH-1 Hunter", "LF-22 Starling"],
    "Annis": ["Elegy Retro Custom", "Apocalypse ZR380", "Savestra", "Elegy RH8", "RE-7B", "Future Shock ZR380", "Nightmare ZR380"],
    "Grotti": ["Cheetah Classic", "Turismo R", "Bestia GTS", "Stinger", "Brioso R/A", "Carbonizzare", "X80 Proto", "Cheetah", "Stinger GT", "Turismo Classic", "Itali GTO", "GT500", "Visione"],
    "Declasse": ["Sabre Turbo Custom", "Gang Burrito", "Tornado", "Voodoo", "Moonbeam", "Rhapsody", "Burrito", "Tampa", "Apocalypse Impaler", "Hotring Sabre", "Tulip", "Rancher XL", "Yosemite", "Moonbeam Custom", "Stallion", "Voodoo Custom", "Nightmare Brutus", "Apocalypse Brutus", "Asea", "Granger", "Premier", "Sabre Turbo", "Vigero", "Tornado Custom", "Drift Tampa", "Mamba", "Burger Shot Stallion", "Tornado Rat Rod", "Weaponized Tampa", "Scramjet", "Future Shock Impaler", "Nightmare Impaler", "Future Shock Brutus", "Vamos", "Impaler"],
    "Shitzu": ["Tropic", "Squalo", "Defiler", "Jetmax", "Hakuchou", "PCJ 600", "Vader", "Suntrap", "Hakuchou Drag"],
    "LCC": ["Hexer", "Sanctus", "Innovation", "Avarus"],
    "Enus": ["Stafford", "Cognoscenti Cabrio", "Huntley S", "Cognoscenti 55 (Armored)", "Cognoscenti 55", "Super Diamond", "Windsor", "Cognoscenti", "Cognoscenti (Armored)", "Windsor Drop"],
    "Western": ["Cliffhanger", "Gargoyle", "Sovereign", "Besra", "Rat Bike", "Daemon", "Bagger", "Nightblade", "Wolfsbane", "Zombie Bobber", "Zombie Chopper", "Future Shock Deathbike", "Nightmare Deathbike", "Apocalypse Deathbike", "Seabreeze", "Rogue"],
    "Mammoth": ["Avenger", "Hydra", "Tula", "Thruster", "Patriot", "Dodo", "Patriot Stretch", "Mogul"],
    "Karin": ["Kuruma (Armored)", "190z", "BeeJay XL", "Intruder", "Sultan", "Technical Aqua", "Technical Custom", "Dilettante", "Futo", "Asterope", "Rusty Rebel", "Rebel", "Sultan RS", "Technical", "Kuruma"],
    "HVY": ["Nightshark", "Mixer", "APC", "Biff", "Barracks Semi", "Forklift", "Future Shock Scarab", "Dozer", "Menacer", "Insurgent", "Cutter", "Dump", "Brickade", "Insurgent Pick-Up Custom", "Insurgent Pick-Up", "Apocalypse Scarab", "Nightmare Scarab"],
    "Schyster": ["Fusilade", "Deviant"],
    "Hijak": ["Khamelion", "Ruston"],
    "MTL": ["Packer", "Future Shock Cerberus", "Flatbed", "Pounder Custom", "Nightmare Cerberus", "Pounder", "Wastelander", "Dune", "Apocalypse Cerberus"],
    "Chariot": ["Romero Hearse"],
    "Weeny": ["Apocalypse Issi", "Issi Classic", "Nightmare Issi", "Future Shock Issi", "Issi"],
    "Principe": ["Lectro", "Deveste Eight", "Diabolus Custom", "Nemesis", "Diabolus"],
    "Pfister": ["Comet SR", "Comet Safari", "Comet", "Comet Retro Custom", "811", "Neon"],
    "BF": ["Surfer", "Injection", "Dune FAV", "Dune Buggy", "Raptor", "Bifta"],
    "Imponte": ["Dukes", "Ruiner", "Ruiner 2000", "Deluxo", "Phoenix", "Nightshade", "Duke O'Death"],
    "Truffade": ["Z-Type", "Nero", "Nero Custom", "Adder"],
    "Maibatsu": ["Sanchez (livery)", "Mule", "Mule Custom", "Penumbra", "Sanchez", "Manchez"],
    "Emperor": ["ETR1", "Habanero"],
    "Ubermacht": ["Sentinel", "Sentinel Classic", "Oracle XS", "Sentinel XS", "SC1", "Oracle", "Zion", "Zion Cabrio", "Revolter"],
    "Lampadati": ["Toro", "Casco", "Michelli GT", "Pigalle", "Tropos Rallye", "Felon", "Felon GT", "Furore GT", "Viseris"],
    "Coil": ["Rocket Voltic", "Cyclone", "Voltic", "Brawler", "Raiden"],
    "Obey": ["9F", "Rocoto", "9F Cabrio", "Tailgater", "Omnis"],
    "Dinka": ["Blista Compact", "Akuma", "Enduro", "Thrust", "Blista", "Double-T", "Marquis", "Vindicator", "Go Go Monkey Blista", "Jester (Racecar)", "Jester", "Jester Classic"],
    "Dewbauchee": ["JB 700", "Specter Custom", "Rapid GT", "Specter", "Vagner", "Rapid GT Classic", "Exemplar", "Massacro (Racecar)", "Seven-70", "Massacro"],
    "Cheval": ["Marshall", "Picador", "Fugitive", "Surge", "Taipan"],
    "Progen": ["GP1", "T20", "Tyrus", "Itali GTB", "Itali GTB Custom"],
    "Vulcar": ["Warrener", "Fagaloa", "Ingot"],
    "Stanley": ["Fieldmaster"],
    "Zirconium": ["Stratum", "Journey"],
    "Overflod": ["Entity XF", "Autarch", "Entity XXR", "Tyrant"],
    "Fathom": ["FQ 2"],
    "Bollokan": ["Prairie"],
    "Speedophile": ["Seashark"],
    "Willard": ["Faction Custom Donk", "Faction", "Faction Custom"],
    "Vom Feuer": ["Anti-Aircraft Trailer"],
    "RUNE": ["Cheburek"]
}